[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[rpc_endpoints]
base_sepolia = "https://base-sepolia.api.onfinality.io/public"
base_mainnet = "https://mainnet.base.org"

# Etherscan v2 API Configuration - Single API key for all chains
etherscan_api_key = "${ETHERSCAN_API_KEY}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
base_sepolia = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${ETHERSCAN_API_KEY}" }