[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

[rpc_endpoints]
base_sepolia = "https://base-sepolia.api.onfinality.io/public"

[etherscan]
base_sepolia = { key = "dummy", url = "https://api-sepolia.basescan.org/api" }